Bookstore/Components/CartSummaryViewComponent.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Bookstore.Models;

namespace Bookstore.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;

        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }

        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

Bookstore/Components/TypesViewComponent.cs
using System;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Bookstore.Models;

namespace Bookstore.Components
{
    public class TypesViewComponent : ViewComponent
    {
        private IBookstoreRepository repo { get; set; }

        public TypesViewComponent(IBookstoreRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];

            var types = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return View(types);
        }
    }
}

Bookstore/Views/Shared/BookSummary.cshtml
@{
}

@model Book

<div class="card card-outline-primary m-1 p-1">

    <div class="bg-light p-1">
        <h4>@Model.Title</h4>

        <span class="badge bg-info" style="float:right">
            Price: @Model.Price
        </span>
    </div>

    <ul>
        <li>Author: @Model.Author</li>
        <li>Publisher: @Model.Publisher</li>
        <li>ISBN: @Model.Isbn</li>
        <li>Classification: @Model.Classification</li>
        <li>Category: @Model.Category</li>
        <li>Number of Pages: @Model.PageCount</li>
    </ul>

    <form method="post" asp-page="/Shop">

        <input type="hidden" asp-for="@Model.BookId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />

        <span class="card-text">
            <button type="submit" class="btn btn-success btn-sm float-right">Add To Cart</button>
        </span>
    </form>

</div>

Bookstore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bookstore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" asp-href-include="/lib/fontawesome/css/*.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            @*<div class="container">*@
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bookstore</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Books</a>
                    </li>
                    @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                </ul>
            </div>
            <div class="pull-right">
                @await Component.InvokeAsync("CartSummary")
            </div>
            @*</div>*@
        </nav>
    </header>

    <blockquote class="blockquote text-center">
        <p class="mb-0">“I don't believe in the kind of magic in my books. But I do believe something very magical can happen when you read a good book.”</p>
        <footer class="blockquote-footer">
            J.K. Rowling author of the
            <cite title="Source Title">Harry Potter Series</cite>
        </footer>
    </blockquote>

    <div class="row m-1 p-1">
        <div id="types" class="col-3">
            <vc:types></vc:types>
        </div>

        <div class="col-9">
            @RenderBody()
        </div>
    </div>

    @*<div class="container">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
        </div>*@

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Bookstore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>